### ISSUE TITLE
typechecking (obey tsconfig.json)

### ISSUE THREAD

**Issue by jonwoodring** [nearbydelta/itypescript#1] opened 2017-02-24 01:12 UTC
How do I get the interpreter to obey tsconfig.json? Right now, it seems to completely ignore typechecking.

I can do something like this
```ts
let add = function(x : number, y : number) { return x + y }
add("x", "y")
```

And it will compile returning "xy".

**Comment by nearbydelta** [comment] 2017-03-03 08:03
Thanks for the comment, and yes, currently it does not obey tsconfig.json because it just transpiles the code. I'm currently looking how to enable typechecking using transpiler, but I didn't find a way yet. When I find it, then I'll update the code. Before then, if you have any idea, please let me know.

**Comment by rafamel** [comment] 2017-05-03 20:42
Having the same issue. Where are we on this @nearbydelta ?

**Comment by nearbydelta** [comment] 2017-07-07 13:05
Sorry for the late update.
Actually I don't have much time to adress this issue last 3 months.
I'm considering to make lib/kernel.js using language service API.
I'll notice you when it'll ready to use, and I'm very sorry for the late update.

**Comment by nearbydelta** [comment] 2017-07-21 17:57
Almost done, using `typescript-simple` package.
Because of the current [issue of typescript-simple](https://github.com/teppeis/typescript-simple/issues/87) package, the current version 0.2.2 is a partial solution for this thread's issue. The issue is that importing modules under semantic typechecking always gives failure, such as 'module not found.' Before this issue is resolved, the semantic checking feature of ITypescript is disabled by default.
If you want to use semantic checking, run ITypescript with `--ts-semantic-chk=on` flag.
I'll notice you when the issue resolved.

**Comment by jchapuis** [comment] 2017-09-08 09:08
Hey, it seems typescript-simple is stuck with this issue, they will not address it. Are you still looking into using the language service APIs instead? It would be fantastic to have both type-checking and usage of modules.

**Comment by nearbydelta** [comment] 2017-09-08 11:12
@jchapuis I'm sorry but I don't because I have not much time for investigating how language service API works. The issue is much more complicated than I expected because,
- The LS API requires "files" to transpile, and outputs "files" (as I know)
- History should be recorded to transpile a single cell whose variables are defined in the other cells.
- It is complicated to check which range of line corresponds to specific cell.

Currently I have not much time to handle these, so it will be grateful that if someone fix this issue...

**Comment by nearbydelta** [comment] 2019-03-17 16:02
This is resolved by using LS API. You can use 0.3.0 version to enable automatic type checking.
Thanks for suggesting LS API, @jchapuis.

**Closed by nearbydelta** 2019-03-17 16:02 UTC
Labels: bug, help wanted
